# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
v = np.array([12,100,12])
print("Memory size of array:", v.itemsize)

Memory size of array: 4


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
x=np.zeros(10)
print(x)
print("Update fith value to 1 ")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fith value to 1 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
v = np.arange(10, 49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
v = v[::-1]
print(v)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
import numpy as np
v = np.arange(0, 9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
import numpy as np
x = np.array([1, 2, 0, 0, 4, 0])
#np.where(x == 0)[0]
#np.nonzero(x)
x[np.nonzero(x)]


array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
#import numpy as np
#x = np.identity(3)
#print(x)

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
import numpy as np
np.random.random((3, 3, 3))

array([[[0.20236606, 0.67951234, 0.2523142 ],
        [0.1242223 , 0.92448903, 0.31362325],
        [0.44104074, 0.78019786, 0.01401752]],

       [[0.29127919, 0.82795146, 0.69860349],
        [0.36834148, 0.59865349, 0.8613399 ],
        [0.28785692, 0.55411872, 0.16174253]],

       [[0.84478403, 0.77819426, 0.93801031],
        [0.0499801 , 0.7945115 , 0.76494157],
        [0.52885716, 0.8439661 , 0.59956964]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
import numpy as np
x=np.random.random((10, 10))
minim_value = np.min(x)
maximum_value = np.max(x)
print(f'Min Value is :{minim_value} Max Value is: {maximum_value}')



Min Value is :0.003149635027215547 Max Value is: 0.9987145448955722


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
x=np.random.random((30))
np.mean(x)

0.4131673186672892

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
two_d = np.ones((5,5))
#print(two_d)
two_d[1:4,1:-1] = 0
print(two_d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
import numpy as np
x= np.ones((3,3))
x = np.pad(x, pad_width=1)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
import numpy as np
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
import numpy as np
#x = np.arange()
#y = x(np.reshape) object is not callable
#y = np.shape(x)
#print(y)
#np.random.random((6 , 7, 8))
np.unravel_index(100, (6, 7, 8))


(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [23]:
import numpy as np
#arr = np.array([0, 1])
#reps = (8,4)
#x = np.tile(arr, reps)
#print(x)
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [24]:

import numpy as np
x = np.random.random((5,5))#.reshape(5,5)
xmax = x.max()
xmin= x.min()
x = (x - xmin)/(xmax - xmin)
print(x)



[[0.10222794 0.61247246 0.79769663 0.04100464 0.09252336]
 [0.18381442 0.08538065 0.80985466 0.00308742 0.        ]
 [0.03664522 0.82271778 0.84331712 0.55780692 0.5493183 ]
 [0.02869766 1.         0.00926729 0.31604606 0.62006798]
 [0.73469462 0.55945329 0.55958284 0.9333119  0.41273738]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [2]:
"""""
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
"""""""""


NameError: name 'np' is not defined

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:

x = np.random.random((5, 3))
y = np.random.random((3, 2))
#print(x,y)
z = np.dot(x, y)
print(z)

[[0.57632513 0.77211301]
 [0.87424939 1.0063977 ]
 [1.05196808 1.19872255]
 [0.88456651 0.88385454]
 [0.88087725 0.49617889]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
x = np.arange(0,11)
x[3:8] = np.multiply(x[3:8],-1)
print(x)


[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:

print(sum(range(5), -1))
from numpy import *
print(sum(range(5)), -1)

9
10 -1


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:

Z = np.arange((3))
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

"""
Z = np.arange((3))
print(Z**Z)
print(2<< Z >> 2)
print (Z <- Z)
print(1j -Z)
print(Z / 1 / 1)
print(Z < Z > Z)

"""


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\dottz\AppData\Local\Temp\ipykernel_14884\1119427974.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\dottz\AppData\Local\Temp\ipykernel_14884\1119427974.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [36]:
import numpy as np
x = np.array((0.4, 1.3, 2.2, 3.4, 4.9, 5.5))
xzero = np.around(x)
print(xzero)


[0. 1. 2. 3. 5. 6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [41]:
x = np.array((0, 1, 2, 3, 4, 5, 6, 7, 8))
y = np.array((0, 2, 4, 6, 8, 10))
print(np.intersect1d(x, y)) 

[0 2 4 6 8]
